{% set name = "pysubgroup" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysubgroup-{{ version }}.tar.gz
  sha256: 1ee5c5c23b0f1c39db27773b3fe991a5a1d6157c253b520a6215a4d07a53c03f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - pip
  run:
    - python >=3.7
    - importlib-metadata
    - pandas >=0.24.0
    - scipy
    - numpy
    - matplotlib-base

test:
  imports:
    - pysubgroup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/flemmerich/pysubgroup
  summary: pysubgroup is a Python library for the data analysis task of subgroup discovery.
  dev_url: https://github.com/flemmerich/pysubgroup
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mgbckr
    - flemmerich
    - Feelx234
