{% set name = "pysubgroup" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysubgroup-{{ version }}.tar.gz
  sha256: f3c9f227da78a3898a81459808e2a0cb0d18d4f3087f7f62483e6c681c65e349

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - pip
  run:
    - python >=3.7
    - importlib-metadata
    - pandas >=0.24.0
    - scipy
    - numpy
    - matplotlib-base

test:
  imports:
    - pysubgroup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/flemmerich/pysubgroup
  summary: pysubgroup is a Python library for the data analysis task of subgroup discovery.
  dev_url: https://github.com/flemmerich/pysubgroup
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mgbckr
    - flemmerich
    - Feelx234
